### ISSUE TITLE
Support for multi-interface instances

### ISSUE THREAD

**Issue by wieshka** [binxio/ec2-elastic-ip-manager#8]
### Description:
I am launching EC2 Instances with AWS::EC2::LaunchTemplate, where in my LaunchTemplate I specify two network interfaces - one in Public, and one in Private Subnet:
```
Resources:
.....
  LaunchTemplate:
    Properties:
        .....................
        NetworkInterfaces:
          - Description: "Public subnet interface"
            SubnetId: !Ref RegionalPublicSubnet
            AssociatePublicIpAddress: false
            DeviceIndex: 0
            Groups:
              - !Ref AllowIngressSecurityGroup
              - !Ref AllowAdminAccessSecurityGroup
              - !Ref LogicalPublicAccessSecurityGroup
            DeleteOnTermination: true
          - Description: "Private subnet interface"
            SubnetId: !Ref RegionalPrivateSubnet
            AssociatePublicIpAddress: false
            DeviceIndex: 1
            Groups:
              - !Ref AllowIngressSecurityGroup
              - !Ref AllowAdminAccessSecurityGroup
            DeleteOnTermination: true
```
Further, I am using this LaunchTemplate as a very generic Template for AutoScaleGroup. Since ~2020 autumn, EC2 ASG Supports LaunchTemplates with multiple NetworkInterfaces, and allows mixing of Public and Private subnets as long as AssociatePublicIpAddress is set to False, even for Public subnets. And that's essentially why I need to automatically assign EIP from the pool - to overcome this limitation. 

### What's wrong (bug):
- After Lambda processes the Instance Launch event, EC2 instance Network interfaces are randomly assigned to either Public or Private subnets, or both. 
- This produces random results - network interfaces can be after Lambda assigned both to Public, in some cases, both to Private, in some cases - properly. 

### Expected result:
- EIP should be allocated only to ["NetworkInterfaces"][0]["NetworkInterfaceId"] as AWS documentation clearly specifies defaults;
- No other allocations should be messed up.

### Additional debug information:
- If I launch instances with Lambda removed/disabled, this behavior can't be reproduced aka its not a bug of LaunchTemplate CloudFormation resource type.
